public class DNA_Sequence {
	public static void main(String[] args) {
		String dnaDatabase =  "CCTGTATTAGGTTCAGAATTCGTTCAGCAGCAGATTCGATTAGCTTTACAACAATTCAATA"+
							  "AAATAGCTTCGCGCTAAATTTTTAACTTTTCTCTGTCGTCGCACAATCGACTTTCTCTGTT"+
							  "TTCTTGTTCAGGGGTTTACCGGAATTGTTTCTGCTGCGATGAGGTATTGCTCGTCAGCCTG"+
							  "AGGCTGAAAATAAAATCCGTGGTCACACCCAATAAGTTAGAGAGAGTACTTTGACTTGGAG"+
							  "CTGGAGGAATTTGACATAGTCGAGTTCAGTTCTTCTCCAAGACGCATCCACGTGAACCGTT"+
							  "GTAACTATGTTCTGTGCCCACACCAAAAAAACTTTCCACGTGAACCGAAAACGAAAGTCTT"+
							  "TGGTTTTAATCAATAAGTGCTCTCTTCTCGGAGAGAGAAGGTGGGCTGCTTGTCTGCCGAT"+
							  "GTACTTTATTAAATCCAATAACCACACCAAAAAAACTTTCCACGTGTGAACTATACTCCAA"+
							  "AAACGAAGTATTGGTTTATCATAATCTGAAAAGTGCAAAGAACGATGATGATGATGATAGA"+
						      "GGAACCTGAGCAGCCATGTCTGAACCTATAGCGTATTGGTCGTCGTGCGACTAAATTAGGT"+
							  "AAAAAAGTAGTTCTAAGAGATTTTGATGATTCAATGCAAAGTTCTATTAATCGTTCAATTG";

		final String DNA = "GTTCAG";
		int firstIndex = dnaDatabase.indexOf(DNA), secondIndex;
		try {
			while(firstIndex >= 0) {
				secondIndex = firstIndex + DNA.length();
				System.out.println(dnaDatabase.charAt(firstIndex - 1)+" "+dnaDatabase.charAt(secondIndex));
				firstIndex = dnaDatabase.indexOf(DNA, firstIndex + 1);
			}
		} catch (StringIndexOutOfBoundsException e) {
			System.out.println("You cannot place the DNA sequence at the beginning/end of the string.");
			System.exit(0);
		}
	}
}